services:
  web_ui:
    container_name: persian-digit-recognition_web_ui
    image: aliinreallife/persian-digit-recognition:latest
    ports:
      - "5000:5000"
  ngrok:
    container_name: persian-digit-recognition_ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NGROK_DOMAIN=${NGROK_DOMAIN}
    command: ["http", "--domain=${NGROK_DOMAIN}", "web_ui:5000"]
    ports:
      - 4040:4040
