version: '3.8'

services:
  web_ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
  ngrok:
      image: ngrok/ngrok:latest
      restart: unless-stopped
      env_file:
        - .env
      environment:
        - NGROK_DOMAIN=${NGROK_DOMAIN}
      command:
        - "http"
        - "--domain=${NGROK_DOMAIN}"
        - "web_ui:5000"
      ports:
        - 4040:4040
